### ISSUE TITLE
Warning in exception manager in IntelliJ 2024.1

### ISSUE THREAD

**Issue by ingokegel** [Camork/file-expander-plugin#40]
In IntelliJ 2024, this started appearing:

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.camork.action.DecompileJarAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.camork.fileExpander]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by Camork** [comment]
Thanks , I will take a fix in this weekend.

**Comment by Camork** [comment]
resolved in v2.5
